---
# Generate ServiceNow instance MID download uri for Linux operating systems

- name: Get ServiceNow build stats
  uri:
    url: "https://{{ now_instance }}/stats.do"
    return_content: yes
  register: now_instance_stats

- name: Get ServiceNow build facts
  set_fact:
    now_instance_build_date: "{{ now_instance_stats.content | regex_search('Build date: ([^<]{1,})') }}"
    now_instance_mid_buildstamp: "{{ now_instance_stats.content | regex_search('MID buildstamp: ([^<]{1,})') }}"
      
- name: Set ServiceNow build facts
  set_fact:
    now_instance_build_date: "{{ now_instance_build_date.split(': ')[1] }}"
    now_instance_mid_buildstamp: "{{ now_instance_mid_buildstamp.split(': ')[1] }}"

- name: Set ServiceNow build dates
  set_fact:
    now_instance_build_1: "{{ now_instance_build_date.split('_')[0].split('-')[2] }}"
    now_instance_build_2: "{{ now_instance_build_date.split('_')[0].split('-')[0] }}"
    now_instance_build_3: "{{ now_instance_build_date.split('_')[0].split('-')[1] }}"

- name:  Set ServiceNow build path
  set_fact:
    now_instance_build: "{{ now_instance_build_1 }}/{{ now_instance_build_2 }}/{{ now_instance_build_3 }}"

- name: Create MID install path
  file:
    path: "{{ now_mid_base_path }}"
    state: directory

- name: Install unzip 
  package:
    name: unzip
    state: present

- name: Download and unzip MID install file
  unarchive:
    src: "{{ now_mid_base_https_uri }}/mid/{{ now_instance_build }}/mid.{{now_instance_mid_buildstamp}}.linux.{{ ansible_architecture | regex_replace('_', '-') }}.zip"
    dest: "{{ now_mid_base_path }}"
    owner: "{{ now_mid_base_user }}"
    group: "{{ now_mid_base_group }}"
    remote_src: yes

- name: Update MID Configuration
  action: template src=templates/config.xml.j2 dest={{ now_mid_base_path }}/agent/config.xml

- name: Update MID shconf override Configuration
  action: template src=templates/mid.shconf_override.j2 dest={{ now_mid_base_path }}/agent/bin/mid.shconf_override

- name: Update MID shconf Configuration
  lineinfile:
     path: "{{ now_mid_base_path }}/agent/bin/mid.shconf"
     # The String to Search
     regexp: "SYSTEMD_KILLMODE=process"
     # The String to Replace
     line: "SYSTEMD_KILLMODE=control-group"
     state: present
     backup: no

- name: Update wrapper-override.conf Configuration java maxmemory
  lineinfile:
    path: "{{ now_mid_base_path }}/agent/conf/wrapper-override.conf"
    # The String to Search
    regexp: "wrapper.java.maxmemory"
    # The String to Replace
    line: "wrapper.java.maxmemory: {{ wrapper_java_maxmemory }}"
    state: present
    backup: no

- name: Change file ownership, group and permissions
  ansible.builtin.file:
    path: /opt/servicenow
    owner: "{{ now_mid_base_user }}"
    group: "{{ now_mid_base_group }}"

- name: Create MID install path
  file:
    path: /var/log/servicenow
    state: directory
    owner: "{{ now_mid_base_user }}"
    group: "{{ now_mid_base_group }}"

- name: Create a symbolic link for the logs
  ansible.builtin.file:
    src: /var/log/servicenow
    dest: "{{ now_mid_base_path }}/agent/logs"
    owner: "{{ now_mid_base_user }}"
    group: "{{ now_mid_base_group }}"
    state: link
    force: yes

- name: Check if MID service exists`
  stat:
    path: /etc/init.d/mid
  register: p

# TODO detect if server daemon already installed
- name: Install MID service
  raw: "{{ now_mid_base_path }}/agent/bin/mid.sh install"
  register: install_result

- name: Bugfix MID service incorrect PIDFile location
  lineinfile:
     path: "/etc/systemd/system/mid.service"
     # The String to Search
     regexp: "../work/mid.pid"
     # The String to Replace
     line: "work/mid.pid"
     state: present
     backup: no

- name: Restart service mid, in all cases, also issue daemon-reload to pick up config changes
  systemd:
    state: restarted
    daemon_reload: yes
    name: mid.service

# the below service does not reload the configuration so it doen not pickup our changes to the file
#- name: Start service mid, if not started
#  service:
#    name: mid.service
#    enabled: true
#    state: reloaded


# The ServiceNow MID configuration file (config.xml) will always appear changed as the mid.instance.password parameter is
# encrypted on first run. Perform a cheap detection of first install through win_lineinfile, however, this will impact change 
# operations such as updating the mid.instance.password.

# - name: MID configuration updated
#   win_lineinfile:
#     dest: "{{ now_mid_base_path }}/agent/config.xml"
#     regexp: <parameter name="mid.instance.password" value="YOUR_INSTANCE_PASSWORD_HERE" encrypt="true"/>$
#     state: absent
#   notify: Update MID configuration (Linux)

# - name: Configure MID service
#   win_service:
#     name: snc_mid
#     start_mode: auto
#     state: started
